-- ========================================================
-- FILE: schema.sql
-- Description: Database Schema for ลาบหนองบัวลำภู POS
-- ========================================================

-- 1. ตารางกลุ่มลูกค้า
CREATE TABLE IF NOT EXISTS public.customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางข้อมูลลูกค้า
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_phone TEXT NOT NULL
);

-- 3. ตารางหมวดหมู่อาหาร
CREATE TABLE IF NOT EXISTS public.food_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- 4. ตารางวัตถุดิบ/สต็อก
CREATE TABLE IF NOT EXISTS public.food_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT NOT NULL,
    quantity NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'ชิ้น',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ตารางผูกเมนูกับสต็อก
CREATE TABLE IF NOT EXISTS public.food_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT REFERENCES public.foods(id),
    stock_id BIGINT REFERENCES public.food_stocks(id),
    stock_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ตารางเมนูอาหาร
CREATE TABLE IF NOT EXISTS public.foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    group_id BIGINT REFERENCES public.food_groups(id),
    price_1 NUMERIC DEFAULT 0.00,
    price_2 NUMERIC DEFAULT 0.00,
    price_3 NUMERIC DEFAULT 0.00,
    requires_stock BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. ตารางสถานที่/แพ
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. ตารางโซนที่นั่ง
CREATE TABLE IF NOT EXISTS public.zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location_id BIGINT REFERENCES public.locations(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. ตารางรายการสั่งซื้อ (Orders)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc'::text, NOW()),
    order_date DATE,
    customer_id BIGINT REFERENCES public.customers(id),
    customer_group_id BIGINT REFERENCES public.customer_groups(id),
    customer_group TEXT,
    phone TEXT,
    customer_phone VARCHAR,
    location_id BIGINT REFERENCES public.locations(id),
    location_name TEXT,
    zone_id BIGINT REFERENCES public.zones(id),
    zone_name TEXT,
    subtotal NUMERIC DEFAULT 0,
    delivery_fee NUMERIC DEFAULT 0,
    total_price NUMERIC,
    total_qty BIGINT DEFAULT 0,
    items JSONB,
    status TEXT DEFAULT 'pending',
    note TEXT
);
