-- ========================================================
-- FILE: schema.sql
-- Auto-generated directly from Supabase via Web HTML
-- Date: 8/9/2569 15:09:34
-- ========================================================

-- ตาราง: customer_groups
CREATE TABLE IF NOT EXISTS public.customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- ตาราง: food_groups
CREATE TABLE IF NOT EXISTS public.food_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- ตาราง: foods
CREATE TABLE IF NOT EXISTS public.foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    requires_stock BOOLEAN DEFAULT TRUE,
    group_id BIGINT REFERENCES public.food_groups(id),
    price_1 NUMERIC DEFAULT 0,
    price_2 NUMERIC DEFAULT 0,
    price_3 NUMERIC DEFAULT 0
);

-- ตาราง: locations
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- ตาราง: zones
CREATE TABLE IF NOT EXISTS public.zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    location_id BIGINT REFERENCES public.locations(id)
);
