-- ========================================================
-- FILE: schema_data.sql
-- Date: 16/9/2569 13:50:04
-- ========================================================

-- TABLE: public.customer_types
CREATE TABLE IF NOT EXISTS public.customer_types (
    customer_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT
);

-- DATA INSERTS: public.customer_types
INSERT INTO public.customer_types (customer_type_id, type) VALUES (1, 'ชาวบ้าน');
INSERT INTO public.customer_types (customer_type_id, type) VALUES (2, 'นักท่องเที่ยว');
INSERT INTO public.customer_types (customer_type_id, type) VALUES (3, 'สบายดี');


-- TABLE: public.customers
CREATE TABLE IF NOT EXISTS public.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.customers
INSERT INTO public.customers (customer_id, name) VALUES (1, 'ร้านอุปกรณ์รถแต่ง');
INSERT INTO public.customers (customer_id, name) VALUES (2, 'ลูกค้าทั่วไป');
INSERT INTO public.customers (customer_id, name) VALUES (3, 'หลานภูสักธาร');
INSERT INTO public.customers (customer_id, name) VALUES (4, 'ยายอาง');
INSERT INTO public.customers (customer_id, name) VALUES (5, 'ร้านสมหมาย');
INSERT INTO public.customers (customer_id, name) VALUES (6, 'ยายเขียว');
INSERT INTO public.customers (customer_id, name) VALUES (7, 'ลุงแอ้');
INSERT INTO public.customers (customer_id, name) VALUES (8, 'ลุงแอ้');
INSERT INTO public.customers (customer_id, name) VALUES (9, 'พม่ามาอยู่');
INSERT INTO public.customers (customer_id, name) VALUES (10, 'Test');
INSERT INTO public.customers (customer_id, name) VALUES (11, 'Tefr');
INSERT INTO public.customers (customer_id, name) VALUES (13, 'แม่บ้าน THE Chill');
INSERT INTO public.customers (customer_id, name) VALUES (12, 'แม่บ้าน THE Chill');
INSERT INTO public.customers (customer_id, name) VALUES (14, 'ทดสอบชาวบ้าน');
INSERT INTO public.customers (customer_id, name) VALUES (15, 'ทดสอบนักท่องเที่ยว');


-- TABLE: public.food_groups
CREATE TABLE IF NOT EXISTS public.food_groups (
    food_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.food_groups
INSERT INTO public.food_groups (food_group_id, name) VALUES (1, 'ข้าว / ข้าวต้ม');
INSERT INTO public.food_groups (food_group_id, name) VALUES (2, 'ข้าวกล่อง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (3, 'ข้าวผัด');
INSERT INTO public.food_groups (food_group_id, name) VALUES (4, 'ต้ม / แกง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (5, 'ทอด / ย่าง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (6, 'ยำ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (7, 'ลาบ / ก้อย / ซอยจุ๊');
INSERT INTO public.food_groups (food_group_id, name) VALUES (8, 'ส้มตำ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (98, 'เมนูพิเศษ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (99, 'ลูกค้าฝากซื้อ');


-- TABLE: public.foods
CREATE TABLE IF NOT EXISTS public.foods (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    food_group_id BIGINT,
    price_1 BIGINT,
    price_2 BIGINT,
    price_3 BIGINT
);

-- DATA INSERTS: public.foods
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (1, 'ข้าวเหนียว', 1, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (51, 'ข้าวต้มทะเล', 1, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (2, 'ข้าวสวย', 1, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (46, 'ขนมจีน', 1, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (48, 'ข้าวต้มกุ้ง', 1, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (49, 'ข้าวต้มหมู', 1, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (50, 'ข้าวต้มไก่', 1, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (33, 'ข้าวไข่เจียว', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (61, 'กระเพราเครื่องในไก่', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (34, 'กระเพราหมู', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (35, 'กระเพราไก่', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (36, 'หมูกระเทียม', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (38, 'กระเพราทะเล', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (32, 'ข้าวผัดหมู', 3, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (15, 'แกงอ่อมหมู', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (16, 'แกงอ่อมเนื้อ', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (13, 'แซ่บเนื้อ', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (14, 'ต้มขม', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (17, 'ต้มยำรวมมิตร', 4, 80, 80, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (12, 'แซ่บกระดูกอ่อน', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (28, 'เนื้อทอด', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (29, 'คอหมูย่าง', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (27, 'หมูทอด', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (26, 'ลวกจิ้ม', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (22, 'ลาบเนื้อ (ดิบ)', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (52, 'ก้อยเนื้อ (สุก)', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (68, 'นิยมไทย 35 (ใหญ่)', 99, 120, 120, 120);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (72, 'เบียร์สิงห์ (ขวด)', 99, 75, 75, 75);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (79, 'น้ำอัดลม (1.25 ลิตร)', 99, 35, 40, 40);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (39, 'กระเพราเนื้อ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (41, 'กระเพราแหนม', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (42, 'กระเพราหมูกรอบ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (43, 'คะน้าหมูกรอบ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (62, 'เนื้อผัดพริกอ่อน', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (63, 'หมูผัดพริกอ่อน', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (55, 'ข้าวผัดทะเล', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (40, 'ข้าวผัดแหนม', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (37, 'ข้าวผัดทะเล', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (65, 'ข้าวผัดกุ้ง', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (31, 'ข้าวผัดไข่', 3, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (67, 'ข้าวผัดไก่', 3, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (82, 'ต้มจืด', 4, 80, 80, 80);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (19, 'ยำมาม่ารวมมิตร', 6, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (18, 'ยำวุ้นเส้นรวมมิตร', 6, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (64, 'กุ้งแช่น้ำปลา', 6, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (53, 'ลาบเนื้อ (สุก)', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (30, 'ซอยจุ๊', 7, 150, 200, 180);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (20, 'ลาบหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (21, 'ก้อยหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (24, 'น้ำตกหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (25, 'ตับหวาน', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (23, 'ก้อยเนื้อ (ดิบ)', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (86, 'ซกเล็ก', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (4, 'ตำถั่ว', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (5, 'ตำไทย', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (6, 'ตำป่า', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (7, 'ตำแตง', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (10, 'ตำกุ้งสด', 8, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (11, 'ตำทะเลรวม', 8, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (8, 'ตำหอยดอง', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (57, 'ตำปู', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (3, 'ตำปูปลาร้า', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (9, 'ตำไทยไข่เค็ม', 8, 70, 80, 70);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (69, 'ตำซั่ว', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (80, 'ตำลาว', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (54, 'ยำปูดอง', 98, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (81, 'LEO ((เล็ก)', 99, 40, 40, 40);


-- TABLE: public.locations
CREATE TABLE IF NOT EXISTS public.locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.locations
INSERT INTO public.locations (location_id, name) VALUES (1, 'เดอะชิลล์');
INSERT INTO public.locations (location_id, name) VALUES (2, 'บาหลี');
INSERT INTO public.locations (location_id, name) VALUES (3, 'บ้านเขา บ้านเรา');
INSERT INTO public.locations (location_id, name) VALUES (4, 'เฮ้ย ! ชิลล์มั้ย');
INSERT INTO public.locations (location_id, name) VALUES (5, 'มาลองเดอร์ลา');
INSERT INTO public.locations (location_id, name) VALUES (6, 'KT Home');
INSERT INTO public.locations (location_id, name) VALUES (7, 'The Brook');
INSERT INTO public.locations (location_id, name) VALUES (8, 'หน้าร้าน');


-- TABLE: public.orders
CREATE TABLE IF NOT EXISTS public.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ,
    total_price BIGINT,
    total_qty BIGINT,
    items JSONB,
    name_phone TEXT,
    customer_type_id BIGINT,
    note TEXT,
    location_id TEXT,
    zone_id TEXT,
    delivery_fee BIGINT,
    subtotal BIGINT,
    customer_id BIGINT
);

-- DATA INSERTS: public.orders
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (39, '2026-09-16T08:17:42.432394+00:00', 50, 1, '[{"qty":1,"name":"หมูผัดพริกอ่อน","note":"","price":50,"food_id":"63","item_id":"1789521450686_u66e","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":50,"friedEggQty":0,"total_price":50,"food_group_id":"1"}]'::jsonb, 'ยายเขียว', 1, '', NULL, NULL, 0, 50, 6);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (40, '2026-09-16T08:18:11.579847+00:00', 140, 1, '[{"qty":1,"name":"หมูทอด","note":"","price":120,"food_id":"27","item_id":"1789521472965_vtll","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":120,"friedEggQty":0,"total_price":120,"food_group_id":"3"}]'::jsonb, 'Test', 2, '', 2, 2, 20, 120, 10);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (41, '2026-09-16T08:18:30.050397+00:00', 100, 1, '[{"qty":1,"name":"ยำมาม่ารวมมิตร","note":"","price":100,"food_id":"19","item_id":"1789521502144_d2ot","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":100,"friedEggQty":0,"total_price":100,"food_group_id":"9"}]'::jsonb, 'ลูกค้าทั่วไป', 3, '', NULL, NULL, 0, 100, NULL);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (42, '2026-09-16T01:18:42.178+00:00', 80, 1, '[{"qty":1,"sum":80,"name":"ค่าอาหารรวม (Quick Order)","note":"","price":80,"food_id":9999,"quantity":1,"food_name":"ค่าอาหารรวม (Quick Order)","unit_price":80,"total_price":80}]'::jsonb, 'ลุงแอ้', 1, '[บันทึกด่วน]', NULL, NULL, 0, 80, 7);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (43, '2026-09-16T01:18:53.35+00:00', 120, 1, '[{"qty":1,"sum":120,"name":"ค่าอาหารรวม (Quick Order)","note":"","price":120,"food_id":9999,"quantity":1,"food_name":"ค่าอาหารรวม (Quick Order)","unit_price":120,"total_price":120}]'::jsonb, '', 2, '[บันทึกด่วน]', 3, 3, 0, 120, NULL);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (38, '2026-09-16T08:17:23.71999+00:00', 60, 1, '[{"qty":1,"name":"กระเพราทะเล","note":"","price":60,"food_id":"38","item_id":"1789521430181_zz4i","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":60,"friedEggQty":0,"total_price":60,"food_group_id":"1"}]'::jsonb, 'แม่บ้าน THE Chill', 1, '', NULL, NULL, 0, 60, 12);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (44, '2026-09-16T01:19:02.792+00:00', 500, 1, '[{"qty":1,"sum":500,"name":"ค่าอาหารรวม (Quick Order)","note":"","price":500,"food_id":9999,"quantity":1,"food_name":"ค่าอาหารรวม (Quick Order)","unit_price":500,"total_price":500}]'::jsonb, '', 2, '[บันทึกด่วน]', NULL, NULL, 0, 500, NULL);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, name_phone, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (45, '2026-09-16T13:48:34.509913+00:00', 50, 1, '[{"qty":1,"name":"ข้าวไข่เจียว","note":"","price":50,"food_id":"33","item_id":"1789540499894_qaqq","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":50,"friedEggQty":0,"total_price":50,"food_group_id":"2"}]'::jsonb, 'ทดสอบชาวบ้าน', 2, '', 8, 8, 0, 50, 14);


-- TABLE: public.zones
CREATE TABLE IF NOT EXISTS public.zones (
    zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    location_id BIGINT
);

-- DATA INSERTS: public.zones
INSERT INTO public.zones (zone_id, name, location_id) VALUES (1, 'Front', 1);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (2, 'Front', 2);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (3, 'Front', 3);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (4, 'Front', 4);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (5, 'Front', 5);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (6, 'Front', 6);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (7, 'Front', 7);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (8, 'Front', 8);

