-- ========================================================
-- FILE: schema_data.sql
-- Date: 17/9/2569 16:31:10
-- ========================================================

-- TABLE: public.customer_types
CREATE TABLE IF NOT EXISTS public.customer_types (
    customer_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT
);

-- DATA INSERTS: public.customer_types
INSERT INTO public.customer_types (customer_type_id, type) VALUES (1, 'ชาวบ้าน');
INSERT INTO public.customer_types (customer_type_id, type) VALUES (2, 'นักท่องเที่ยว');
INSERT INTO public.customer_types (customer_type_id, type) VALUES (3, 'สบายดี');


-- TABLE: public.customers
CREATE TABLE IF NOT EXISTS public.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.customers
INSERT INTO public.customers (customer_id, name) VALUES (1, 'ไอ้ไก่');
INSERT INTO public.customers (customer_id, name) VALUES (2, 'รปภ.ดำ');
INSERT INTO public.customers (customer_id, name) VALUES (3, 'พี่เอ.สบายดี');
INSERT INTO public.customers (customer_id, name) VALUES (4, 'คนงาน.สบายดี');
INSERT INTO public.customers (customer_id, name) VALUES (5, 'ลุงแอ้');


-- TABLE: public.food_groups
CREATE TABLE IF NOT EXISTS public.food_groups (
    food_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.food_groups
INSERT INTO public.food_groups (food_group_id, name) VALUES (1, 'ข้าว / ข้าวต้ม');
INSERT INTO public.food_groups (food_group_id, name) VALUES (2, 'ข้าวกล่อง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (3, 'ข้าวผัด');
INSERT INTO public.food_groups (food_group_id, name) VALUES (4, 'ต้ม / แกง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (5, 'ทอด / ย่าง');
INSERT INTO public.food_groups (food_group_id, name) VALUES (6, 'ยำ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (7, 'ลาบ / ก้อย / ซอยจุ๊');
INSERT INTO public.food_groups (food_group_id, name) VALUES (8, 'ส้มตำ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (98, 'เมนูพิเศษ');
INSERT INTO public.food_groups (food_group_id, name) VALUES (99, 'ลูกค้าฝากซื้อ');


-- TABLE: public.foods
CREATE TABLE IF NOT EXISTS public.foods (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    food_group_id BIGINT,
    price_1 BIGINT,
    price_2 BIGINT,
    price_3 BIGINT
);

-- DATA INSERTS: public.foods
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (21, 'ลาบเนื้อ', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (19, 'ลาบหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (35, 'หมูกระเทียม', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (26, 'หมูทอด', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (18, 'ยำรวมมิตร (วุ้นเส้น)', 6, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (3, 'ตำปูปลาร้า', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (6, 'ตำป่า', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (9, 'ตำไทยไข่เค็ม', 8, 70, 80, 70);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (5, 'ตำไทย', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (4, 'ตำถั่ว', 8, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (7, 'ตำแตง', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (11, 'ตำทะเลรวม', 8, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (10, 'ตำกุ้งสด', 8, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (8, 'ตำหอยดอง', 8, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (34, 'กระเพราไก่', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (37, 'กระเพราทะเล', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (38, 'กระเพราเนื้อ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (33, 'กระเพราหมู', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (22, 'ก้อยเนื้อ', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (20, 'ก้อยหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (16, 'แกงอ่อมเนื้อ', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (15, 'แกงอ่อมหมู', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (32, 'ข้าวไข่เจียว', 2, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (30, 'ข้าวผัดไข่', 3, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (36, 'ข้าวผัดทะเล', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (31, 'ข้าวผัดหมู', 3, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (2, 'ข้าวสวย', 1, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (1, 'ข้าวเหนียว', 1, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (28, 'คอหมูย่าง', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (29, 'ซอยจุ๊', 7, 150, 200, 180);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (12, 'แซ่บกระดูกอ่อน', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (13, 'แซ่บเนื้อ', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (14, 'ต้มขม', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (17, 'ต้มยำรวมมิตร', 4, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (24, 'ตับหวาน', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (23, 'น้ำตกหมู', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (27, 'เนื้อทอด', 5, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (25, 'ลวกจิ้ม', 7, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (41, 'กระเพราหมูกรอบ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (40, 'กระเพราแหนม', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (39, 'ข้าวผัดแหนม', 3, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (42, 'คะน้าหมูกรอบ', 2, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (44, 'ยําวุ้นเส้น (มาม่า)', 6, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (46, 'ข้าวต้มทะเล', 98, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (47, 'ขนมจีน', 98, 10, 10, 10);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (48, 'ข้าวต้มกุ้ง', 98, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (49, 'ข้าวต้มหมู', 98, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (50, 'ข้าวต้มไก่', 98, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (51, 'กระเพราเครื่องในไก่', 98, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (52, 'ต้มยำรวมมิตร', 98, 80, 80, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (58, 'เนื้อผัดพริกอ่อน', 98, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (59, 'หมูผัดพริกอ่อน', 98, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (60, 'ข้าวผัดกุ้ง', 98, 60, 60, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (61, 'ข้าวผัดไก่', 98, 50, 50, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (62, 'ต้มจืด', 98, 80, 80, 80);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (65, 'กุ้งแช่น้ำปลา', 98, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (68, 'ซกเล็ก', 98, 80, 120, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (69, 'ตำหอยดอง', 98, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (70, 'ตำปู', 98, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (71, 'ตำซั่ว', 98, 60, 70, 60);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (72, 'ตำลาว', 98, 50, 60, 50);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (73, 'ยำปูดอง', 98, 100, 100, 100);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (74, 'LEO ((เล็ก)', 99, 40, 40, 40);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (57, 'น้ำอัดลม (1.25 ลิตร)', 99, 35, 40, 40);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (43, 'ไก่ย่าง', 98, 200, 250, 220);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (55, 'นิยมไทย 35 (ใหญ่)', 99, 120, 120, 120);
INSERT INTO public.foods (food_id, name, food_group_id, price_1, price_2, price_3) VALUES (56, 'เบียร์สิงห์ (ขวด)', 99, 75, 75, 75);


-- TABLE: public.locations
CREATE TABLE IF NOT EXISTS public.locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- DATA INSERTS: public.locations
INSERT INTO public.locations (location_id, name) VALUES (1, 'เดอะชิลล์');
INSERT INTO public.locations (location_id, name) VALUES (2, 'บาหลี');
INSERT INTO public.locations (location_id, name) VALUES (3, 'บ้านเขา บ้านเรา');
INSERT INTO public.locations (location_id, name) VALUES (4, 'เฮ้ย ! ชิลล์มั้ย');
INSERT INTO public.locations (location_id, name) VALUES (5, 'มาลองเดอร์ลา');
INSERT INTO public.locations (location_id, name) VALUES (6, 'KT Home');
INSERT INTO public.locations (location_id, name) VALUES (7, 'The Brook');
INSERT INTO public.locations (location_id, name) VALUES (8, 'หน้าร้าน');


-- TABLE: public.orders
CREATE TABLE IF NOT EXISTS public.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ,
    total_price BIGINT,
    total_qty BIGINT,
    items JSONB,
    nickname TEXT,
    customer_type_id BIGINT,
    note TEXT,
    location_id BIGINT,
    zone_id BIGINT,
    delivery_fee BIGINT,
    subtotal BIGINT,
    customer_id TEXT
);

-- DATA INSERTS: public.orders
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (1, '2026-09-16T11:56:11.662+00:00', 600, 1, '[{"qty":1,"sum":600,"name":"ค่าอาหารรวม (Quick Order)","note":"","price":600,"food_id":9999,"quantity":1,"food_name":"ค่าอาหารรวม (Quick Order)","unit_price":600,"total_price":600}]'::jsonb, '', 2, '[บันทึกด่วน]', 8, 8, 0, 600, NULL);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (2, '2026-09-16T18:57:02.609354+00:00', 80, 1, '[{"qty":1,"name":"น้ำตกหมู","note":"","price":80,"food_id":"24","item_id":"1789559798474_hisq","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":80,"friedEggQty":0,"total_price":80,"food_group_id":"7"}]'::jsonb, 'ไอ้ไก่', 1, '', NULL, NULL, 0, 80, 1);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (3, '2026-09-16T18:57:41.097359+00:00', 80, 1, '[{"qty":1,"name":"ก้อยเนื้อ (ดิบ)","note":"","price":80,"food_id":"23","item_id":"1789559847194_md2o","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":80,"friedEggQty":0,"total_price":80,"food_group_id":"7"}]'::jsonb, 'รปภ.ดำ', 1, '', NULL, NULL, 0, 80, 2);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (4, '2026-09-16T18:58:18.267076+00:00', 50, 1, '[{"qty":1,"name":"ตำปูปลาร้า","note":"","price":50,"food_id":"3","item_id":"1789559878888_9yxl","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":50,"friedEggQty":0,"total_price":50,"food_group_id":"8"}]'::jsonb, 'พี่เอ.สบายดี', 1, '', NULL, NULL, 0, 50, 3);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (5, '2026-09-16T19:01:56.75124+00:00', 100, 1, '[{"qty":1,"name":"ยำมาม่ารวมมิตร","note":"","price":100,"food_id":"19","item_id":"1789559950968_d2tv","is_custom":true,"omeletQty":0,"base_price":100,"totalPrice":100,"unit_price":100,"friedEggQty":0,"total_price":100,"food_group_id":"6"}]'::jsonb, 'คนงาน.สบายดี', 1, '', NULL, NULL, 0, 100, 4);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (6, '2026-09-16T19:03:58.424588+00:00', 110, 2, '[{"qty":1,"name":"ไก่ผัดพริกอ่อน","note":"","price":50,"food_id":"special_item","item_id":"1789560215728_xmes","category":"เมนูพิเศษ","is_custom":true,"omeletQty":0,"is_special":true,"totalPrice":60,"unit_price":60,"friedEggQty":1,"total_price":60,"category_name":"เมนูพิเศษ","food_group_id":"special","isCustomPrice":true},{"qty":1,"name":"หมูกระเทียม","note":"","price":50,"food_id":"36","item_id":"1789560186929_smo9","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":50,"friedEggQty":0,"total_price":50,"food_group_id":"2"}]'::jsonb, 'ลูกค้าทั่วไป', 3, '', NULL, NULL, 0, 110, NULL);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (8, '2026-09-16T19:29:32.315383+00:00', 80, 1, '[{"qty":1,"name":"ก้อยหมู","note":"","price":80,"food_id":"21","item_id":"1789561747563_wal4","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":80,"friedEggQty":0,"total_price":80,"food_group_id":"7"}]'::jsonb, 'ลุงแอ้', 1, '', NULL, NULL, 0, 80, 5);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (7, '2026-09-16T19:06:40.786746+00:00', 90, 2, '[{"qty":1,"name":"ข้าวเหนียว","note":"","price":10,"food_id":"1","item_id":"1789560332483_xmtk","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":10,"friedEggQty":0,"total_price":10,"food_group_id":"1"},{"qty":1,"name":"เนื้อทอด","note":"","price":80,"food_id":"28","item_id":"1789560326927_zi4q","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":80,"friedEggQty":0,"total_price":80,"food_group_id":"5"}]'::jsonb, 'คนงาน.เดอะชิลล์', 1, '', NULL, NULL, 0, 90, 4);
INSERT INTO public.orders (order_id, created_at, total_price, total_qty, items, nickname, customer_type_id, note, location_id, zone_id, delivery_fee, subtotal, customer_id) VALUES (9, '2026-09-17T15:36:46.073081+00:00', 190, 3, '[{"qty":1,"name":"ตำปูปลาร้า","note":"","price":50,"food_id":"3","item_id":"1789634142379_dyyb","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":50,"friedEggQty":0,"total_price":50,"food_group_id":"8","isSpecialMenu":false},{"qty":1,"name":"ตำหอยดอง","note":"","price":60,"food_id":"8","item_id":"1789634137762_30ma","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":60,"friedEggQty":0,"total_price":60,"food_group_id":"8","isSpecialMenu":false},{"qty":1,"name":"น้ำตกหมู","note":"","price":80,"food_id":"23","item_id":"1789634127655_nw8p","is_custom":false,"omeletQty":0,"base_price":null,"totalPrice":null,"unit_price":80,"friedEggQty":0,"total_price":80,"food_group_id":"7","isSpecialMenu":false}]'::jsonb, 'ไอ้ไก่', 1, '', NULL, NULL, 0, 190, 1);


-- TABLE: public.zones
CREATE TABLE IF NOT EXISTS public.zones (
    zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    location_id BIGINT
);

-- DATA INSERTS: public.zones
INSERT INTO public.zones (zone_id, name, location_id) VALUES (1, 'Front', 1);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (2, 'Front', 2);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (3, 'Front', 3);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (4, 'Front', 4);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (5, 'Front', 5);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (6, 'Front', 6);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (7, 'Front', 7);
INSERT INTO public.zones (zone_id, name, location_id) VALUES (8, 'Front', 8);

